name: Multipack
version: '1.0'
main: net.tjalp.multipack.Multipack
api-version: '1.21'
authors: [ tjalp ]
description: Allows you to set multiple resource packs for your Minecraft server, without merging them
website: https://tjalp.net/
